AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "examples/**/*"

Layout/LineLength:
  Max: 1000

Metrics/AbcSize:
  Max: 200
Metrics/BlockLength:
  Max: 1000
Metrics/BlockNesting:
  Max: 4
Metrics/ClassLength:
  Max: 1000
Metrics/CyclomaticComplexity:
  Max: 60
Metrics/MethodLength:
  Max: 100
Metrics/ModuleLength:
  Max: 1000
Metrics/ParameterLists:
  MaxOptionalParameters: 6
  Max: 50
Metrics/PerceivedComplexity:
  Max: 50
