AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "examples/**/*"

    # Bundler vendored gems / dependencies (do not lint)
    - "vendor/**/*"
    - "bundle/**/*"

    # Common generated / third-party directories
    - "tmp/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "coverage/**/*"
    - ".bundle/**/*"

Layout/LineLength:
  Max: 1000

Metrics/AbcSize:
  Max: 200

Metrics/BlockLength:
  Max: 1000

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 1000

Metrics/CyclomaticComplexity:
  Max: 60

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 1000

Metrics/ParameterLists:
  MaxOptionalParameters: 6
  Max: 50

Metrics/PerceivedComplexity:
  Max: 50